podman-desktop/e2e

README.md
docs/extend.md
docs/running.md

Add documentation about the project

---

test/e2e/e2e_podman/suite_test.go
test/extended/podman-desktop/elements.go
test/extended/podman-desktop/podman-desktop.go

Change-Id: I9688d13be166a7a56e3fabcd36dd682f316cd847

fix: typo error on Welcome

---

.gitignore

Change-Id: I6916e950a2a48d4b27a2aa9a922b3fd0e85d4e53

chore: ignore out directory for git

---

Makefile
OWNERS
README.md
go.mod
test/e2e/e2e_podman/podman-extension_test.go
test/e2e/e2e_podman/suite_test.go
test/extended/podman-desktop/extension/podman/podman-extension_darwin.go
test/extended/podman-desktop/extension/podman/podman-extension_windows.go
test/extended/podman-desktop/extension/podman/podman-extesion.go
test/extended/podman-desktop/podman-desktop.go

Move to Containers org

---

.github/workflows/windows.yaml

chore: add gh action for windows desktop

---

.github/workflows/build.yaml
.github/workflows/tkn-bundle.yaml

Omit triggers of the GHA builds when only a github workflow has changed

---

oci/lib/windows/run.ps1

Install WSL version 2 without distribution

---

.github/workflows/podman-desktop-e2e-windows.yaml

Workflow works on my [fork], latest updates and other minor fixes.
[fork]: https://github.com/odockal/podman-desktop-e2e/actions/runs/6563318002

Update podman desktop e2e playwright workflow

---

.github/workflows/windows.yaml

chore: add podman functional e2e testing on windows fix #19

---

.github/workflows/podman-nightly-e2e.yaml

Fixed #48 
Active run at my fork: https://github.com/odockal/podman-desktop-e2e/actions/runs/6574359437
Lets wait for it to finish.

Update podman nightly with playwright e2e tests workflow

---

.github/workflows/podman-desktop-e2e-windows.yaml
.github/workflows/podman-nightly-e2e.yaml
.github/workflows/windows.yaml

Include Junit Reporter step in testing workflows

---

.github/workflows/podman-nightly-e2e.yaml

chore(ci): update podman development version in podman nightly workflow

---

.github/workflows/podman-desktop-e2e-nightly-windows.yaml
.github/workflows/podman-desktop-e2e-windows.yaml

Fixes #74.
Podman Desktop e2e full suite now green with fixes done on our side: https://github.com/containers/podman-desktop/actions/runs/7267745574/job/19802197187.

fix: switch to stable e2e suite for podman desktop

---

.github/workflows/desktop-e2e-podman-windows-matrix.yaml

Podman Desktop e2e with Preinstalled podman Matrix workflow

---

tkn/task.yaml

* Added cleanup target folder to true as default
* Only run frdp (fake rdp) sidecar for windows

Improvements on tekton task spec

---

.github/workflows/build.yaml
oci/lib/darwin/run.sh
tkn/task.yaml

Fix runtime issues on mac

---

.github/workflows/desktop-e2e-podman-windows-matrix.yaml
.github/workflows/podman-desktop-e2e-nightly-windows.yaml
.github/workflows/podman-desktop-e2e-windows.yaml
.github/workflows/podman-e2e-windows.yaml

Solution for issue https://github.com/containers/podman-desktop-e2e/issues/104.

Added env var for registry authentication into the e2e workflows

---

oci/lib/darwin/run.sh
oci/lib/windows/run.ps1

Ensure no previous instance of Podman Desktop is running on target host

---

test/extended/podman-desktop/extension/podman/podman-extension_darwin.go

Check for select location during Podman installation

---

tkn/task.yaml

chore: fake vnc connection if testing darwin

---

.github/workflows/build.yaml
go.mod

Upgrade go version

---

.github/workflows/build.yaml
.github/workflows/desktop-e2e-podman-windows-matrix.yaml
.github/workflows/desktop-e2e-test-job-windows.yaml
.github/workflows/podman-desktop-e2e-nightly-windows.yaml
.github/workflows/podman-desktop-e2e-windows.yaml
.github/workflows/podman-e2e-windows.yaml
.github/workflows/tkn-bundle.yaml

Updating pde2e images. Adding also a testing workflow for various new enhancements.
The update of the image version should also include new node version.
fixes: #132 #131 #135

Update the pde2e image versions and os, add testing workflow

---

.github/workflows/desktop-e2e-podman-windows-matrix.yaml
.github/workflows/desktop-e2e-test-job-windows.yaml
.github/workflows/podman-desktop-e2e-nightly-windows.yaml
.github/workflows/podman-desktop-e2e-windows.yaml

Add option to pass env. vars, secrets and fixes for script names

---

.github/workflows/desktop-e2e-podman-windows-matrix.yaml
.github/workflows/desktop-e2e-test-job-windows.yaml
.github/workflows/podman-desktop-e2e-nightly-windows.yaml

Fixes #156.
Upversions podman dev branch to 5.1.0-dev.
Add a permission check to a test job (so it can be then tried and applied on others). #150

Upversion podman version in the workflows to latest dev: 5.1.0

---

.github/workflows/sso-e2e-nightly-windows.yaml

Add sso e2e nightly windows workflow

---

.github/workflows/sso-e2e-nightly-windows.yaml

Fix SSO workflow errors

---

.github/workflows/podman-desktop-e2e-windows.yaml

Enable wslInstallFix during Podman installation goax test

---

test/extended/podman-desktop/podman-desktop.go

Increase a timeout for a podman-desktop executable to appear

---

.github/workflows/desktop-e2e-test-job-windows.yaml

chore(ci): add option to choose podman provider in debug wf

---

.github/workflows/desktop-e2e-podman-windows-matrix.yaml
.github/workflows/podman-desktop-e2e-nightly-windows.yaml

fixes #https://github.com/containers/podman-desktop-e2e/issues/223

chore: remove podman version paramter since it is not used

---

test/e2e/e2e_podman/suite_test.go
test/extended/podman-desktop/podman-desktop.go

chore: add timeout while waiting for telemetry checkbox click action

---

.github/workflows/desktop-e2e-podman-windows-matrix.yaml

related issue: https://github.com/containers/podman-desktop-e2e/issues/242

chore: Switch the pde2e image version to the latest published versions

---

.github/workflows/podman-desktop-e2e-nightly-windows.yaml
.github/workflows/podman-desktop-e2e-windows.yaml

related issue: https://github.com/containers/podman-desktop-e2e/issues/242

chore: Switch the pde2e image default version to the latest.

---

.github/workflows/podman-desktop-e2e-nightly-windows-hyperv.yaml
.github/workflows/podman-desktop-e2e-nightly-windows-wsl.yaml

https://github.com/containers/podman-desktop-e2e/issues/241

Run nightly e2e tests with hyperv virtualization provider

---

.github/workflows/desktop-e2e-podman-windows-matrix.yaml
.github/workflows/desktop-e2e-test-job-windows.yaml
.github/workflows/podman-desktop-e2e-nightly-windows-hyperv.yaml

Switches the previous installation of podman (zip archive) to using the setup.exe version. Fixes #240

chore: switch to podman setup.exe

---

.github/workflows/podman-desktop-e2e-remote-windows.yaml

Fixes https://github.com/podman-desktop/podman-desktop/issues/8633
Requires: https://github.com/podman-desktop/podman-desktop/pull/9858
Requires: https://github.com/odockal/pde2e-runner/pull/8

chore(ci): add podman-remote testing workflow for windows

---

.github/workflows/podman-desktop-e2e-kubernetes.yaml

issue: https://github.com/podman-desktop/e2e/issues/272

ci: run kubernetes e2e tests separately 

---

.github/workflows/desktop-e2e-podman-windows-matrix.yaml
.github/workflows/desktop-e2e-test-job-windows.yaml
.github/workflows/podman-desktop-e2e-kubernetes.yaml
.github/workflows/podman-desktop-e2e-nightly-windows-hyperv.yaml
.github/workflows/podman-desktop-e2e-nightly-windows-wsl.yaml
.github/workflows/podman-desktop-e2e-remote-windows.yaml
.github/workflows/podman-desktop-e2e-windows.yaml

chore: update pde2e-* images versions to 0.0.3

---

test/extended/podman-desktop/elements.go

nit: update welcome screen button text in pd

---

.github/workflows/desktop-e2e-podman-windows-matrix.yaml
.github/workflows/desktop-e2e-test-job-windows.yaml
.github/workflows/podman-desktop-e2e-kubernetes.yaml
.github/workflows/podman-desktop-e2e-nightly-windows-hyperv.yaml
.github/workflows/podman-desktop-e2e-nightly-windows-wsl.yaml
.github/workflows/podman-desktop-e2e-remote-windows.yaml
.github/workflows/podman-desktop-e2e-windows.yaml
.github/workflows/podman-e2e-windows.yaml
.github/workflows/prerelease-desktop-e2e-debug-job-windows.yaml

chore: update all mapt image usages to 0.7.3

---

.github/workflows/desktop-e2e-podman-windows-matrix.yaml
.github/workflows/desktop-e2e-test-job-windows.yaml
.github/workflows/podman-desktop-e2e-kubernetes.yaml
.github/workflows/podman-desktop-e2e-nightly-windows-hyperv.yaml
.github/workflows/podman-desktop-e2e-nightly-windows-wsl.yaml
.github/workflows/podman-desktop-e2e-remote-windows.yaml
.github/workflows/podman-desktop-e2e-windows.yaml
.github/workflows/podman-e2e-windows.yaml
.github/workflows/prerelease-desktop-e2e-debug-job-windows.yaml

Should include the fix for https://github.com/redhat-developer/mapt/issues/385 / https://github.com/podman-desktop/e2e/issues/303.

build: bump up mapt to 0.7.4

---

.github/workflows/desktop-e2e-podman-windows-matrix.yaml

issue: https://github.com/podman-desktop/e2e/issues/267

chore(ci): exclude user-networking run with hyperv provider

---

.github/workflows/podman-desktop-e2e-stress-ui-windows.yaml

Fixes some extra characters that shouldn't be on the stress yaml file

test(e2e): fix errata stress workflow

---

.github/workflows/podman-desktop-e2e-kubernetes.yaml

issue: https://github.com/podman-desktop/e2e/issues/326

chore(ci): setup timeout for kubernetes workflow

---

.github/workflows/podman-desktop-e2e-remote-windows.yaml

chore: update and fix remote e2e tests workflow

---

.github/workflows/podman-desktop-e2e-stress-ui-linux.yaml
.github/workflows/podman-desktop-e2e-stress-ui-windows.yaml

test(e2e): add workflow to run ui stress test on linux

---

.github/workflows/podman-desktop-e2e-stress-ui-windows.yaml

Solves https://github.com/podman-desktop/e2e/issues/346

test(e2e): fix ui stress tests on windows

---

.github/workflows/podman-desktop-e2e-stress-ui-linux.yaml
.github/workflows/podman-desktop-e2e-stress-ui-windows.yaml

Fixes https://github.com/podman-desktop/podman-desktop/issues/12058

chore: keep traces and videos on ui stress tests

---

.github/workflows/podman-desktop-e2e-nightly-windows-wsl.yaml

https://github.com/podman-desktop/e2e/issues/373

chore(test): add cli tools env var to workflow

---

.github/workflows/desktop-e2e-podman-windows-matrix.yaml
.github/workflows/desktop-e2e-test-job-windows.yaml
.github/workflows/podman-desktop-e2e-kubernetes.yaml
.github/workflows/podman-desktop-e2e-nightly-windows-hyperv.yaml
.github/workflows/podman-desktop-e2e-nightly-windows-wsl.yaml
.github/workflows/podman-desktop-e2e-remote-windows.yaml
.github/workflows/podman-desktop-e2e-stress-ui-windows.yaml
.github/workflows/podman-desktop-e2e-windows.yaml
.github/workflows/podman-e2e-windows.yaml
.github/workflows/prerelease-desktop-e2e-debug-job-windows.yaml

We need to change the reference for create action to main to grab latest changes.

chore(ci): change create action reference to main

---

.github/workflows/desktop-e2e-podman-windows-matrix.yaml
.github/workflows/desktop-e2e-test-job-windows.yaml
.github/workflows/podman-desktop-e2e-kubernetes.yaml
.github/workflows/podman-desktop-e2e-nightly-windows-hyperv.yaml
.github/workflows/podman-desktop-e2e-nightly-windows-wsl.yaml
.github/workflows/podman-desktop-e2e-remote-windows.yaml
.github/workflows/podman-desktop-e2e-stress-ui-linux.yaml
.github/workflows/podman-desktop-e2e-stress-ui-windows.yaml
.github/workflows/podman-desktop-e2e-windows.yaml
.github/workflows/podman-e2e-windows.yaml
.github/workflows/prerelease-desktop-e2e-debug-job-windows.yaml

chore(ci): fixing incorrect MAPT region parsing, removing incorrect env variables

---

.github/actions/run-playwright-test/action.yml
.github/workflows/podman-desktop-e2e-windows.yaml

chore(ci): update workflow

---

.github/workflows/desktop-e2e-podman-windows-matrix.yaml
.github/workflows/desktop-e2e-test-job-windows.yaml
.github/workflows/podman-desktop-e2e-kubernetes.yaml
.github/workflows/podman-desktop-e2e-nightly-windows-hyperv.yaml
.github/workflows/podman-desktop-e2e-nightly-windows-wsl.yaml
.github/workflows/podman-desktop-e2e-remote-windows.yaml
.github/workflows/podman-desktop-e2e-stress-ui-linux.yaml
.github/workflows/podman-desktop-e2e-stress-ui-windows.yaml
.github/workflows/podman-desktop-e2e-testing-farm.yaml
.github/workflows/podman-desktop-e2e-windows.yaml
.github/workflows/podman-e2e-windows.yaml
.github/workflows/prerelease-desktop-e2e-debug-job-windows.yaml

issue: https://github.com/podman-desktop/e2e/issues/485

chore: align run and artifact names across workflows
